[package]

name = "statrs"
version = "0.13.0"
authors = ["Michael Ma"]
description = "Statistical computing library for Rust"
license = "MIT"
keywords = ["probability", "statistics", "stats", "distribution", "math"]
categories = ["science"]
documentation = "https://docs.rs/statrs/0.13.0/statrs/"
homepage = "https://github.com/boxtown/statrs"
repository = "https://github.com/boxtown/statrs"
edition = "2018"

[lib]

name = "statrs"
path = "src/lib.rs"

[dependencies]
rand = "0.7"
nalgebra = "0.19"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "order_statistics"
harness = false