[package]

name = "statrs"
version = "0.8.0"
authors = ["Michael Ma"]
description = "Statistical computing library for Rust"
license = "MIT"
keywords = ["probability", "statistics", "stats", "distribution", "math"]
categories = ["science"]
documentation = "https://docs.rs/statrs/0.8.0/statrs/"
homepage = "https://github.com/boxtown/statrs"
repository = "https://github.com/boxtown/statrs"

[lib]

name = "statrs"
path = "src/lib.rs"

[dependencies]
rand = "0.3"